version: "3"

# networks:
#   my_network:
#     driver: bridge

services:
  backend:
    build:
      context: ./apps/api/core
      dockerfile: Dockerfile
    command: /app/start.sh
    volumes:
      - ./apps/api/core:/app
    ports:
      - 8000:8000
      # - "8001:8000"   # Port mapping for the second replica
      # - "8002:8000"   # Port mapping for the third replica
    # networks:
    #   - my_network
    depends_on:
      - postgresql
      - redis
      - rabbitmq
    # deploy:
    #   replicas: 3  # Set the desired number of replicas

  postgresql:
    image: postgres:latest
    container_name: db_malhuza
    environment:
      - POSTGRES_USER=sahal
      - POSTGRES_PASSWORD=09876
      - POSTGRES_DB=malhuza
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_malhuza
    ports:
      - 5672:5672
      - 15672:15672
    # networks:
    #   - my_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data
    # networks:
    #   - my_network

  worker:
    build: 
      context: ./apps/api/core
      dockerfile: Dockerfile
    command: /app/worker.sh
    volumes:
      - ./apps/api/core:/app
    depends_on:
      - redis
      - postgresql
    # networks:
    #   - my_network
      
volumes:
  redis_data:
  postgresql_data:
