version: '3.1'

services:
  content:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      NODE_ENV: production
    networks:
      - app-network
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: sahal
      MONGO_INITDB_ROOT_PASSWORD: 09876
      MONGO_INITDB_DATABASE: content
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
