# Generated by Django 4.2.4 on 2023-11-29 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=355)),
                ('content', models.TextField(blank=True, null=True)),
                ('coverImage', models.CharField(blank=True, max_length=500, null=True)),
                ('icon', models.CharField(blank=True, max_length=500, null=True)),
                ('isArchived', models.BooleanField(default=False)),
                ('isPublished', models.BooleanField(default=False)),
                ('parentDocument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
