# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: 'apps/web/'

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: |
        touch .env
        echo "${{secrets.PROD_WEB_ENV}}" > .env
    - run: export NODE_OPTIONS=--max-old-space-size=32768
    - run: npm ci
    - run: NODE_OPTIONS='--max_old_space_size=4096' npm run build
    - name: Content Service Set Env 
      working-directory: 'apps/api/content'
      run: |
        touch .env
        echo "${{secrets.PROD_CONTENT_ENV}}" > .env
    - name: Content Service Install Dependencie
      working-directory: 'apps/api/content'
      run: npm ci
    - name: Restart Content Service
      working-directory: 'apps/api/content'
      run: pm2 restart contentService
